apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: stwomack/orders-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-secret