apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: orders-service-image
  namespace: default
spec:
  tag: stwomack/orders-service
  serviceAccountName: wiz-service-account
  builder:
    name: main-builder
    kind: Builder
  source:
    git:
      url: https://github.com/stwomack/orders-service
      revision: wiz
