apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: orders-service-image-tmp
  namespace: default
spec:
  tag: stwomack/orders-service
  serviceAccountName: tutorial-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/stwomack/orders-service
      revision: master
